# https://starship.rs/config/

format = """\
  $time\
  $custom\
  $username\
  $hostname\
  $kubernetes\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $docker_context\
  $package\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $golang\
  $java\
  $julia\
  $nim\
  $nodejs\
  $ocaml\
  $php\
  $purescript\
  $python\
  $ruby\
  $rust\
  $terraform\
  $zig\
  $nix_shell\
  $conda\
  $memory_usage\
  $aws\
  $env_var\
  $crystal\
  $cmd_duration\
  $line_break\
  $jobs\
  $battery\
  $character\
"""

[aws]
disabled = true
# yellow
style = "bold 136"
symbol = "  "

[battery]
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

# "bold red" style when capacity is between 0% and 10%
[[battery.display]]
threshold = 10
style = "bold 124"

# "bold yellow" style when capacity is between 10% and 30%
[[battery.display]]
threshold = 30
style = "bold 136"

[buf]
symbol = " "

[c]
symbol = " "

[character]
# Replace the "❯" symbol in the prompt with "♠"
# black
success_symbol = "[♠](bold 0)"
# red
error_symbol = "[✖](bold 124)"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
# bold green
style = "bold 64"
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[env_var]
variable = "VAULT_ADDR"

[fossil_branch]
symbol = " "

[git_branch]
# bold violet
style = "bold 61"
symbol = " "

[git_state]
cherry_pick = "🍒 PICKING"
# bold yellow
style = "bold 136"

[git_status]
# Show ahead/behind count of the branch being tracked
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
# default, bold blue
style = "bold 33"
# cyan
conflicted = "[=](37)"
# black
deleted = "[✘](0)"
# red
modified = "[!](124)"
# default
# renamed = '»'
# green
staged = "[+](64)"
# yellow
stashed = '[\$](136)'
# orange
untracked = "[?](166)"

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
# yellow
# style = "bold dimmed 136"
# red
style = "bold 124"
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[terraform]
# This is very slow currently, so it is disabled by default
# show_version = true

[time]
disabled = false
format = "🕙 [$time]($style) "
time_format = "%T"

[username]
show_always = true
# bold orange
style_user = "bold 166"
